# Generated by Django 5.1.1 on 2024-09-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_authoruser_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authoruser',
            name='cover',
            field=models.ImageField(blank=True, default='media/user/base/base_cover.jpeg', null=True, upload_to='media/user/%Y/%m/%d/'),
        ),
    ]
