# Generated by Django 5.1.1 on 2024-09-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=155)),
                ('cover', models.ImageField(upload_to='media/%Y/%m/%d/')),
            ],
        ),
    ]
