# Generated by Django 5.1.1 on 2024-09-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_echo', '0002_posts_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='cover',
            field=models.ImageField(null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
