# Generated by Django 5.1.1 on 2024-09-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_echo', '0003_alter_posts_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(default='default', max_length=55),
        ),
        migrations.AlterField(
            model_name='posts',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
