# Generated by Django 5.1.1 on 2024-09-29 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_echo', '0004_posts_title_alter_posts_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.CharField(max_length=55),
        ),
    ]
