# Generated by Django 5.1.1 on 2024-09-30 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_authoruser_cover'),
        ('social_echo', '0005_alter_posts_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='author_cover',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authors.authoruser'),
        ),
    ]
