# Generated by Django 5.1.1 on 2024-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_echo', '0006_posts_author_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
