# Generated by Django 5.1.1 on 2024-11-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_echo', '0008_alter_posts_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='slug',
        ),
    ]
